---
- name: Import inventory audit playbook
  import_playbook: "/workspace/playbooks/inventory_name.yaml"

- name: Import Nginx audit playbook
  import_playbook: "/workspace/playbooks/nginx_check.yml"

- name: Import Linux audit playbook
  import_playbook: "/workspace/playbooks/linux_check.yml"